#!/usr/bin/env python3
"""
compare_methylation.py – Run four global distribution tests and per-site
statistical tests with flat 2D count arrays for replicate detection.

Count format:
- Single replicate: shape (n_sites, 2) -> [[meth, unmeth], ...]
- Multiple replicates: shape (n_sites, 2*n_replicates) -> [[meth1, unmeth1, meth2, unmeth2], ...]

Usage example
-------------
import numpy as np
from compare_methylation import compare_methylomes

# Single replicate: (n_sites, 2)
counts_a = np.array([[10, 5], [15, 8], [3, 12]])
counts_b = np.array([[8, 7], [12, 3], [5, 10]])

# Two replicates: (n_sites, 4)
counts_a = np.array([[10, 5, 8, 7], [15, 8, 12, 3]])
counts_b = np.array([[8, 7, 6, 9], [10, 5, 14, 1]])_a, beta_b, counts_a, counts_b)
print(results['global_table'])
results['per_site_df'].to_csv('per_site_results.tsv', sep='\t', index=False)
"""

from __future__ import annotations
import numpy as np
import pandas as pd
from scipy import stats
from scipy.optimize import minimize
from statsmodels.stats.multitest import multipletests
import warnings
import math
import polars as pl

# ------------------------------------------------------------------
# Core helper functions
# ------------------------------------------------------------------

def _permute_p(stat_fn, data_a, data_b, n_perm: int, seed: int = 1) -> tuple[float, float]:
    """Return (observed_stat, permutation_p)."""
    rng = np.random.default_rng(seed)
    obs = stat_fn(data_a, data_b)
    pool = np.concatenate([data_a, data_b])
    n_a = len(data_a)
    more_extreme = 0
    for _ in range(n_perm):
        rng.shuffle(pool)
        perm_a, perm_b = pool[:n_a], pool[n_a:]
        more_extreme += stat_fn(perm_a, perm_b) >= obs
    pval = (more_extreme + 1) / (n_perm + 1)   # add-one smoothing
    return obs, pval


def _ks_bootstrap(data1, data2, n_permutations: int, seed: int) -> tuple[float, tuple]:
    """
    Performs a two-sample permutation test based on the Kolmogorov-Smirnov statistic.

    This implements Stephen's null hypothesis: that both samples are drawn from the
    same underlying distribution. It calculates the KS statistic (D) for the observed
    data and compares it to a distribution of KS statistics generated by repeatedly
    permuting the combined data and splitting it back into two samples.

    Args:
        data1 (array-like): First sample data.
        data2 (array-like): Second sample data.
        n_permutations (int): The number of permutations to perform.

    Returns:
        float: The empirical p-value based on the permutations.
            Returns None if either sample has fewer than 2 data points.
    """
    np.random.seed(seed)  # Ensure reproducibility

    # Convert to numpy arrays for easier handling
    data1 = np.asarray(data1)
    data2 = np.asarray(data2)

    # KS test requires at least 2 points in each sample for meaningful comparison often,
    # although ks_2samp might handle 1. Let's stick to the original check.
    if len(data1) < 5 or len(data2) < 5:
        # Cannot perform meaningful KS test
        print("Unexpected data size for KS test. Returning None.")
        return None, None

    # Calculate the observed KS statistic (D)
    # ks_2samp returns a result object (or tuple in older scipy)
    # The first element or the .statistic attribute is the D value.
    observed_ks_value = stats.ks_2samp(data1, data2).statistic
    
    if np.isnan(observed_ks_value) or np.isinf(observed_ks_value):
        # If the observed KS value is NaN or infinite, we cannot proceed
        print("Observed KS value is NaN or infinite. Returning None.")
        return None, None

    # Combine the data for permutation
    combined_data = np.concatenate((data1, data2))
    n1 = len(data1)
    
    # Cap permutations
    n_permutations = min(math.comb(len(combined_data), n1), n_permutations)

    count_extreme = 0
    for _ in range(n_permutations):
        # Permute the combined data
        np.random.shuffle(combined_data)
        
        # Split into two samples
        permuted_sample1 = combined_data[:n1]
        permuted_sample2 = combined_data[n1:]

        # Calculate KS statistic for the permuted samples
        perm_ks_value = stats.ks_2samp(permuted_sample1, permuted_sample2).statistic

        if perm_ks_value >= observed_ks_value:
            count_extreme += 1

    return (count_extreme + 1) / (n_permutations + 1), observed_ks_value


def _parse_counts_to_replicates(counts_flat):
    """
    Parse flat count array into replicate structure.
    
    Parameters
    ----------
    counts_flat : array-like, shape (n_replicates * 2,)
        Flat array [meth1, unmeth1, meth2, unmeth2, ...]
    
    Returns
    -------
    array-like, shape (n_replicates, 2)
        Structured as [[meth1, unmeth1], [meth2, unmeth2], ...]
    """
    counts_flat = np.asarray(counts_flat)
    n_values = len(counts_flat)
    
    if n_values % 2 != 0:
        raise ValueError(f"Count array length must be even, got {n_values}")
    
    n_replicates = n_values // 2
    return counts_flat.reshape(n_replicates, 2)


def _beta_binomial_ll(params, meth_counts, total_counts):
    """
    Compute negative log-likelihood for beta-binomial model[7][10].
    
    Parameters
    ----------
    params : array-like
        [alpha, beta] parameters for beta-binomial
    meth_counts : array-like
        Number of methylated reads per replicate
    total_counts : array-like  
        Total reads per replicate
    
    Returns
    -------
    float
        Negative log-likelihood
    """
    alpha, beta = params
    if alpha <= 0 or beta <= 0:
        return np.inf
    
    # Use scipy's betabinom logpmf for numerical stability[10]
    ll = stats.betabinom.logpmf(meth_counts, total_counts, alpha, beta).sum()
    return -ll


def _binomial_ll(p, meth_counts, total_counts):
    """
    Compute negative log-likelihood for binomial model.
    
    Parameters
    ----------
    p : float
        Probability of success (methylation probability)
    meth_counts : array-like
        Number of methylated reads per replicate
    total_counts : array-like
        Total reads per replicate
    
    Returns
    -------
    float
        Negative log-likelihood
    """
    if p <= 0 or p >= 1:
        return np.inf
    
    ll = stats.binom.logpmf(meth_counts, total_counts, p).sum()
    return -ll


def _beta_binomial_lrt(site_counts_a, site_counts_b):
    """
    Perform likelihood ratio test between beta-binomial and binomial models[2][5].
    
    Tests H0: data follows binomial (no overdispersion)
    vs H1: data follows beta-binomial (overdispersion present)
    
    Parameters
    ----------
    site_counts_a, site_counts_b : array-like
        Flat arrays that will be parsed into replicate structure
    
    Returns
    -------
    tuple
        (p_value, test_method)
    """
    try:
        # Parse into replicate structure
        counts_a = _parse_counts_to_replicates(site_counts_a)
        counts_b = _parse_counts_to_replicates(site_counts_b)
        
        # Extract methylated and total counts
        meth_a, total_a = counts_a[:, 0], counts_a.sum(axis=1)
        meth_b, total_b = counts_b[:, 0], counts_b.sum(axis=1)
        
        # Filter zero coverage
        valid_a = total_a > 0
        valid_b = total_b > 0
        
        if not (np.any(valid_a) and np.any(valid_b)):
            return 1.0, "no_coverage"
        
        meth_a, total_a = meth_a[valid_a], total_a[valid_a]
        meth_b, total_b = meth_b[valid_b], total_b[valid_b]
        
        # Combine both groups for model fitting
        meth_all = np.concatenate([meth_a, meth_b])
        total_all = np.concatenate([total_a, total_b])
        
        # Need at least 3 observations for meaningful overdispersion test
        if len(meth_all) < 3:
            return 1.0, "insufficient_data"
        
        # Fit binomial model (H0: no group difference, no overdispersion)
        p_pooled = meth_all.sum() / total_all.sum()
        ll_binomial = -_binomial_ll(p_pooled, meth_all, total_all)
        
        # Fit beta-binomial model (H1: allows overdispersion, group differences)
        # Use method of moments for initial estimates
        p_hat = meth_all.sum() / total_all.sum()
        alpha_init = p_hat * 10
        beta_init = (1 - p_hat) * 10
        
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            result = minimize(
                _beta_binomial_ll,
                [alpha_init, beta_init],
                args=(meth_all, total_all),
                method='L-BFGS-B',
                bounds=[(0.01, 1000), (0.01, 1000)]
            )
        
        if not result.success:
            # Fallback to pooled Fisher exact test
            return _pooled_fisher_test(site_counts_a, site_counts_b)
        
        ll_betabinom = -result.fun
        
        # Likelihood ratio test statistic[2][5]
        # df = 1 (beta-binomial has 1 extra parameter vs binomial)
        lrt_stat = 2 * (ll_betabinom - ll_binomial)
        
        # Handle boundary case where chi2 test is conservative[5]
        # Use 50:50 mixture of point mass at 0 and chi2(1)
        if lrt_stat <= 0:
            pval = 1.0
        else:
            pval = 0.5 * (1 + stats.chi2.sf(lrt_stat, df=1))
        
        return pval, "beta_binomial_lrt"
        
    except Exception:
        # Final fallback to pooled Fisher exact
        return _pooled_fisher_test(site_counts_a, site_counts_b)


def _pooled_fisher_test(counts_a_flat, counts_b_flat):
    """Fallback pooled Fisher exact test."""
    try:
        counts_a = _parse_counts_to_replicates(counts_a_flat)
        counts_b = _parse_counts_to_replicates(counts_b_flat)
        
        meth_a_total = counts_a[:, 0].sum()
        unmeth_a_total = counts_a[:, 1].sum()
        meth_b_total = counts_b[:, 0].sum()  
        unmeth_b_total = counts_b[:, 1].sum()
        
        table = np.array([[meth_a_total, unmeth_a_total],
                         [meth_b_total, unmeth_b_total]])
        _, pval = stats.fisher_exact(table, alternative="two-sided")
        return pval, "fisher_pooled"
    except Exception:
        return 1.0, "failed"


def _per_site_test(site_counts_a_flat, site_counts_b_flat):
    """
    Dispatch appropriate test based on replicate structure.
    
    Parameters
    ----------
    site_counts_a_flat, site_counts_b_flat : array-like
        Flat arrays of length 2*n_replicates
    
    Returns
    -------
    tuple
        (p_value, test_method, n_replicates_a, n_replicates_b)
    """
    try:
        # Determine number of replicates from array length
        n_replicates_a = len(site_counts_a_flat) // 2
        n_replicates_b = len(site_counts_b_flat) // 2
        
        # Single replicate case
        if n_replicates_a == 1 and n_replicates_b == 1:
            ma, ua = site_counts_a_flat[0], site_counts_a_flat[1]
            mb, ub = site_counts_b_flat[0], site_counts_b_flat[1]
            table = np.array([[ma, ua], [mb, ub]])
            try:
                _, pval = stats.fisher_exact(table, alternative="two-sided")
                return pval, "fisher_single", n_replicates_a, n_replicates_b
            except Exception:
                return 1.0, "fisher_failed", n_replicates_a, n_replicates_b
        
        # Multiple replicates - use beta-binomial LRT
        pval, method = _beta_binomial_lrt(site_counts_a_flat, site_counts_b_flat)
        return pval, method, n_replicates_a, n_replicates_b
        
    except Exception:
        return 1.0, "failed", 0, 0

# ------------------------------------------------------------------
# Public API
# ------------------------------------------------------------------

def compare_methylomes(
    beta_a: np.ndarray,
    beta_b: np.ndarray,
    counts_a: np.ndarray | None = None,
    counts_b: np.ndarray | None = None,
    *,
    n_perm: int = 10_000,
    n_boot: int = 5_000,
    alpha: float = 0.05,
    seed: int = 1,
) -> dict:
    """
    Compare two methylomes with flat 2D count arrays.
    
    Parameters
    ----------
    beta_a, beta_b : array-like
        Methylation fractions for samples A and B
    counts_a, counts_b : array-like, optional
        Count arrays with shape (n_sites, 2*n_replicates):
        - (n_sites, 2): Single replicate -> [[meth, unmeth], ...]
        - (n_sites, 4): Two replicates -> [[meth1, unmeth1, meth2, unmeth2], ...]
        - (n_sites, 2*n): n replicates -> [[meth1, unmeth1, ..., methn, unmethn], ...]
    n_perm : int, default 10000
        Number of permutations for global tests
    n_boot : int, default 5000
        Number of bootstrap samples for KS confidence interval
    alpha : float, default 0.05
        Significance threshold for FDR correction
    seed : int, default 1
        Random seed for reproducibility
    
    Returns
    -------
    dict
        Dictionary with keys 'global_table' (str) and 'per_site_df' (DataFrame)
    """
    beta_a = np.asarray(beta_a, dtype=float)
    beta_b = np.asarray(beta_b, dtype=float)
    assert beta_a.shape == beta_b.shape, "Beta arrays must be same length"

    # --------------------------------------------------------------
    # 1. Global tests
    # --------------------------------------------------------------
    # (a) Bootstrapped KS
    p_value, d_value = _ks_bootstrap(beta_a, beta_b, n_boot, seed)

    # (b) Wasserstein distance (W1)
    w1_stat, w1_p = _permute_p(stats.wasserstein_distance, beta_a, beta_b, n_perm, seed)

    # (c) Energy distance
    ed_stat, ed_p = _permute_p(stats.energy_distance, beta_a, beta_b, n_perm, seed)

    # (d) Epps-Singleton
    es_res = stats.epps_singleton_2samp(beta_a, beta_b)

    # Assemble global table
    global_table = pl.DataFrame({
        "Test": [
            "Kilmogorov-Smirnov",
            "1-Wasserstein",
            "Energy distance",
            "Epps-Singleton χ²"
        ],
        "Statistic": [
            d_value,
            w1_stat,
            ed_stat,
            es_res.statistic
        ],
        "p-value": [
            p_value,
            w1_p,
            ed_p,
            es_res.pvalue
        ],
        "Notes": [
            "non-parametric; bootstrapped",
            "interpretable in β-units",
            "metric; EDF-weighted",
            "robust to ties"
        ]
    })
    
    # Assemble human-readable table
    global_table_str = (
        "| Test | Statistic | p-value | Notes |\n"
        "|---|---|---|---|\n"
        f"| KS D (bootstrap) | {d_value:.4f} | {p_value:.4g} | non-parametric |\n"
        f"| 1-Wasserstein | {w1_stat:.4f} | {w1_p:.4g} | interpretable in β-units |\n"
        f"| Energy distance | {ed_stat:.4f} | {ed_p:.4g} | metric; EDF-weighted |\n"
        f"| Epps-Singleton χ² | {es_res.statistic:.2f} | {es_res.pvalue:.4g} | robust to ties |"
    )

    # --------------------------------------------------------------
    # 2. Per-site tests with flat 2D count array parsing
    # --------------------------------------------------------------
    if counts_a is not None and counts_b is not None:
        counts_a = np.asarray(counts_a)
        counts_b = np.asarray(counts_b)
        
        # Validate input format
        if counts_a.ndim != 2 or counts_b.ndim != 2:
            raise ValueError("Count arrays must be 2-dimensional")
        
        n_sites_a, n_cols_a = counts_a.shape
        n_sites_b, n_cols_b = counts_b.shape
        
        if n_sites_a != n_sites_b:
            raise ValueError("Count arrays must have same number of sites")
        
        if n_cols_a % 2 != 0 or n_cols_b % 2 != 0:
            raise ValueError("Count array columns must be even (2*n_replicates)")
        
        if n_sites_a != len(beta_a):
            raise ValueError("Count arrays must match beta array length")
        
        pvals = []
        test_methods = []
        n_replicates_a_list = []
        n_replicates_b_list = []
        
        for site_counts_a, site_counts_b in zip(counts_a, counts_b):
            pval, method, n_rep_a, n_rep_b = _per_site_test(site_counts_a, site_counts_b)
            pvals.append(pval)
            test_methods.append(method)
            n_replicates_a_list.append(n_rep_a)
            n_replicates_b_list.append(n_rep_b)
        
        # FDR correction
        pvals = np.array(pvals)
        reject, qvals, *_ = multipletests(pvals, alpha=alpha, method="fdr_bh")
        
        per_site_df = pd.DataFrame({
            "index": np.arange(len(beta_a)),
            "beta_A": beta_a,
            "beta_B": beta_b,
            "n_replicates_A": n_replicates_a_list,
            "n_replicates_B": n_replicates_b_list,
            "test_method": test_methods,
            "p_raw": pvals,
            "q_BH": qvals,
            "significant": reject,
        })
    else:
        per_site_df = None  # empty frame when no counts provided

    return {"global_table": global_table, "global_table_str": global_table_str, "per_site_df": per_site_df}
