#!/usr/bin/env python3
"""
compare_methylome.py – Run four global distribution tests and per-site
statistical tests with flat 2D count arrays for replicate detection.

Count format:
- Single replicate: shape (n_sites, 2) -> [[meth, unmeth], ...]
- Multiple replicates: shape (n_sites, 2*n_replicates) -> [[meth1, unmeth1, meth2, unmeth2], ...]

Usage example
-------------
import numpy as np
from compare_methylome import compare_methylomes

# Single replicate: (n_sites, 2)
counts_a = np.array([[10, 5], [15, 8], [3, 12]])
counts_b = np.array([[8, 7], [12, 3], [5, 10]])

# Two replicates: (n_sites, 4)
counts_a = np.array([[10, 5, 8, 7], [15, 8, 12, 3]])
counts_b = np.array([[8, 7, 6, 9], [10, 5, 14, 1]])_a, beta_b, counts_a, counts_b)
print(results['global_table'])
results['per_site_df'].to_csv('per_site_results.tsv', sep='\t', index=False)
"""

from __future__ import annotations
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats.multitest import multipletests
import math
import polars as pl
from src.objects.motif import Motif


# ------------------------------------------------------------------
# Core helper functions
# ------------------------------------------------------------------

def _permute_p(stat_fn, data_a, data_b, n_perm: int, seed: int = 1) -> tuple[float, float]:
    """Return (observed_stat, permutation_p)."""
    rng = np.random.default_rng(seed)
    obs = stat_fn(data_a, data_b)
    pool = np.concatenate([data_a, data_b])
    n_a = len(data_a)
    more_extreme = 0
    for _ in range(n_perm):
        rng.shuffle(pool)
        perm_a, perm_b = pool[:n_a], pool[n_a:]
        more_extreme += stat_fn(perm_a, perm_b) >= obs
    pval = (more_extreme + 1) / (n_perm + 1)   # add-one smoothing
    return obs, pval


def _ks_bootstrap(data1, data2, n_permutations: int, seed: int) -> tuple[float, tuple]:
    """
    Performs a two-sample permutation test based on the Kolmogorov-Smirnov statistic.

    This implements Stephen's null hypothesis: that both samples are drawn from the
    same underlying distribution. It calculates the KS statistic (D) for the observed
    data and compares it to a distribution of KS statistics generated by repeatedly
    permuting the combined data and splitting it back into two samples.

    Args:
        data1 (array-like): First sample data.
        data2 (array-like): Second sample data.
        n_permutations (int): The number of permutations to perform.

    Returns:
        float: The empirical p-value based on the permutations.
            Returns None if either sample has fewer than 2 data points.
    """
    np.random.seed(seed)  # Ensure reproducibility

    # Convert to numpy arrays for easier handling
    data1 = np.asarray(data1)
    data2 = np.asarray(data2)

    # KS test requires at least 2 points in each sample for meaningful comparison often,
    # although ks_2samp might handle 1. Let's stick to the original check.
    if len(data1) < 5 or len(data2) < 5:
        # Cannot perform meaningful KS test
        print("Unexpected data size for KS test. Returning None.")
        return None, None

    # Calculate the observed KS statistic (D)
    # ks_2samp returns a result object (or tuple in older scipy)
    # The first element or the .statistic attribute is the D value.
    observed_ks_value = stats.ks_2samp(data1, data2).statistic
    
    if np.isnan(observed_ks_value) or np.isinf(observed_ks_value):
        # If the observed KS value is NaN or infinite, we cannot proceed
        print("Observed KS value is NaN or infinite. Returning None.")
        return None, None

    # Combine the data for permutation
    combined_data = np.concatenate((data1, data2))
    n1 = len(data1)
    
    # Cap permutations
    n_permutations = min(math.comb(len(combined_data), n1), n_permutations)

    count_extreme = 0
    for _ in range(n_permutations):
        # Permute the combined data
        np.random.shuffle(combined_data)
        
        # Split into two samples
        permuted_sample1 = combined_data[:n1]
        permuted_sample2 = combined_data[n1:]

        # Calculate KS statistic for the permuted samples
        perm_ks_value = stats.ks_2samp(permuted_sample1, permuted_sample2).statistic

        if perm_ks_value >= observed_ks_value:
            count_extreme += 1

    return (count_extreme + 1) / (n_permutations + 1), observed_ks_value


def _per_site_test(site_counts_a_flat, site_counts_b_flat):
    """
    Dispatch appropriate test based on replicate structure.


    Parameters
    ----------
    site_counts_a_flat, site_counts_b_flat : array-like
        Flat arrays of length 2*n_replicates


    Returns
    -------
    tuple
        (p_value, test_method, n_replicates_a, n_replicates_b)
    """
    try:
        n_replicates_a = len(site_counts_a_flat) // 2
        n_replicates_b = len(site_counts_b_flat) // 2


        # Single replicate case
        if n_replicates_a == 1 and n_replicates_b == 1:
            ma, ua = site_counts_a_flat[0], site_counts_a_flat
            mb, ub = site_counts_b_flat, site_counts_b_flat
            table = np.array([[ma, ua], [mb, ub]])
            try:
                res = stats.chi2_contingency(table)
                return res.pvalue, "chi2_single", n_replicates_a, n_replicates_b
            except Exception:
                return 1.0, "chi2_failed", n_replicates_a, n_replicates_b


        # Multiple replicate case
        else:
            # Build within-group tables
            a_table = np.array(site_counts_a_flat).reshape(n_replicates_a, 2)
            b_table = np.array(site_counts_b_flat).reshape(n_replicates_b, 2)


            # Test for consistency within replicates: 2xN table for each group
            try:
                a_pval = stats.chi2_contingency(a_table).pvalue if n_replicates_a > 1 else 1.0
                b_pval = stats.chi2_contingency(b_table).pvalue if n_replicates_b > 1 else 1.0
            except Exception:
                return 1.0, "replicates_test_failed", n_replicates_a, n_replicates_b


            # If replicates differ within A or B, reject test, no pooling
            if a_pval < 0.05 or b_pval < 0.05:
                return 1.0, "replicates_inconsistent", n_replicates_a, n_replicates_b


            # Pool replicates for A and B
            pooled_a = np.sum(a_table, axis=0)
            pooled_b = np.sum(b_table, axis=0)
            table = np.array([pooled_a, pooled_b])


            try:
                pval = stats.chi2_contingency(table).pvalue
                return pval, "chi2_pooled", n_replicates_a, n_replicates_b
            except Exception:
                return 1.0, "chi2_failed", n_replicates_a, n_replicates_b


    except Exception:
        return 1.0, "failed", 0, 0

    
# ------------------------------------------------------------------
# Public API
# ------------------------------------------------------------------

def compare_methylomes(
    beta_a: np.ndarray,
    beta_b: np.ndarray,
    counts_a: pl.DataFrame | None = None,
    counts_b: pl.DataFrame | None = None,
    *,
    n_perm: int = 10_000,
    n_boot: int = 5_000,
    alpha: float = 0.05,
    seed: int = 1,
    motif: Motif = None
) -> dict:
    """
    Compare two methylomes with flat 2D count arrays.
    
    Parameters
    ----------
    beta_a, beta_b : array-like
        Methylation fractions for samples A and B
    counts_a, counts_b : array-like, optional
        Count arrays with shape (n_sites, 2*n_replicates):
        - (n_sites, 2): Single replicate -> [[meth, unmeth], ...]
        - (n_sites, 4): Two replicates -> [[meth1, unmeth1, meth2, unmeth2], ...]
        - (n_sites, 2*n): n replicates -> [[meth1, unmeth1, ..., methn, unmethn], ...]
    n_perm : int, default 10000
        Number of permutations for global tests
    n_boot : int, default 5000
        Number of bootstrap samples for KS confidence interval
    alpha : float, default 0.05
        Significance threshold for FDR correction
    seed : int, default 1
        Random seed for reproducibility
    
    Returns
    -------
    dict
        Dictionary with keys 'global_table' (str) and 'per_site_df' (DataFrame)
    """
    beta_a = np.asarray(beta_a, dtype=float)
    beta_b = np.asarray(beta_b, dtype=float)
    assert beta_a.shape == beta_b.shape, "Beta arrays must be same length"

    # --------------------------------------------------------------
    # 1. Global tests
    # --------------------------------------------------------------
    # (a) Bootstrapped KS
    p_value, d_value = _ks_bootstrap(beta_a, beta_b, n_boot, seed)

    # (b) Wasserstein distance (W1)
    w1_stat, w1_p = _permute_p(stats.wasserstein_distance, beta_a, beta_b, n_perm, seed)

    # (c) Energy distance
    ed_stat, ed_p = _permute_p(stats.energy_distance, beta_a, beta_b, n_perm, seed)

    # (d) Epps-Singleton
    es_res = stats.epps_singleton_2samp(beta_a, beta_b)

    # Assemble global table
    global_table = pl.DataFrame({
        "Test": [
            "Kilmogorov-Smirnov",
            "1-Wasserstein",
            "Energy distance",
            "Epps-Singleton χ²"
        ],
        "Statistic": [
            d_value,
            w1_stat,
            ed_stat,
            es_res.statistic
        ],
        "p-value": [
            p_value,
            w1_p,
            ed_p,
            es_res.pvalue
        ],
        "Notes": [
            "non-parametric; bootstrapped",
            "interpretable in β-units",
            "metric; EDF-weighted",
            "robust to ties"
        ]
    })
    
    # Assemble human-readable table
    global_table_str = (
        "| Test | Statistic | p-value | Notes |\n"
        "|---|---|---|---|\n"
        f"| KS D (bootstrap) | {d_value:.4f} | {p_value:.4g} | non-parametric |\n"
        f"| 1-Wasserstein | {w1_stat:.4f} | {w1_p:.4g} | interpretable in β-units |\n"
        f"| Energy distance | {ed_stat:.4f} | {ed_p:.4g} | metric; EDF-weighted |\n"
        f"| Epps-Singleton χ² | {es_res.statistic:.2f} | {es_res.pvalue:.4g} | robust to ties |"
    )

    # --------------------------------------------------------------
    # 2. Per-site tests with flat 2D count array parsing
    # --------------------------------------------------------------
    if counts_a is not None and counts_b is not None:    
        pvals = []
        test_methods = []
        n_replicates_a_list = []
        n_replicates_b_list = []
        contigs = []
        strands = []
        positions = []
        
        for site_counts_a, site_counts_b in zip(counts_a.group_by("contig", "strand", "position", maintain_order=True), counts_b.group_by("contig", "strand", "position", maintain_order=True)):
            site_counts_a_df = (site_counts_a[1].with_columns(pl.struct("contig", "strand", "position").cum_count().over(pl.struct("contig", "strand", "position")).alias("replicate"))
                                .pivot(
                                    values=[motif.meth_type, motif.canonical_base],
                                    index=["contig", "strand", "position"],
                                    columns="replicate"
                                ))

            replicates = sorted(set(int(c.split('_')[-1]) for c in site_counts_a_df.columns if '_' in c))
            desired_cols = [f"{v}_{r}" for r in replicates for v in [motif.meth_type, motif.canonical_base] if f"{v}_{r}" in site_counts_a_df.columns]
            site_counts_a_df = site_counts_a_df.select(desired_cols).to_numpy()
            
            site_counts_b_df = (site_counts_b[1].with_columns(pl.struct("contig", "strand", "position").cum_count().over(pl.struct("contig", "strand", "position")).alias("replicate"))
                                .pivot(
                                    values=[motif.meth_type, motif.canonical_base],
                                    index=["contig", "strand", "position"],
                                    columns="replicate"
                                ))

            replicates = sorted(set(int(c.split('_')[-1]) for c in site_counts_b_df.columns if '_' in c))
            desired_cols = [f"{v}_{r}" for r in replicates for v in [motif.meth_type, motif.canonical_base] if f"{v}_{r}" in site_counts_b_df.columns]
            site_counts_b_df = site_counts_b_df.select(desired_cols).to_numpy()
            
            pval, method, n_rep_a, n_rep_b = _per_site_test(site_counts_a_df[0], site_counts_b_df[0])
            pvals.append(pval)
            test_methods.append(method)
            n_replicates_a_list.append(n_rep_a)
            n_replicates_b_list.append(n_rep_b)
            contig, strand, position = site_counts_a[0][0], site_counts_a[0][1], site_counts_a[0][2]
            contigs.append(contig)
            strands.append(strand)
            positions.append(position)
            
        # FDR correction
        pvals = np.array(pvals)
        reject, qvals, *_ = multipletests(pvals, alpha=alpha, method="fdr_tsbh")
        
        per_site_df = pl.from_dict({
            "contig": contigs,
            "strand": strands,
            "position": positions,
            "beta_A": beta_a,
            "beta_B": beta_b,
            "n_replicates_A": n_replicates_a_list,
            "n_replicates_B": n_replicates_b_list,
            "test_method": test_methods,
            "p_raw": pvals,
            "q_BH": qvals,
            "significant": reject,
        })
    else:
        per_site_df = None  # empty frame when no counts provided

    return {"global_table": global_table, "global_table_str": global_table_str, "per_site_df": per_site_df}
