import click
from pathlib import Path
from src.objects.genome import Genome
from analysis import (
    plot_whole_methylome,
    plot_motif_methylation_distribution,
    plot_dmr_scores_heatmap,
    plot_parallel_categories_methylation,
    extract_diff_methylated_genes
)


@click.group(help="A multi-command CLI for methylation analysis.")
@click.pass_context
def cli(ctx):
    """
    The main entry point for our CLI tool.

    Running `python cli.py --help` or `python cli.py -h` will show
    the top-level help, which includes available commands.
    """
    pass


@cli.command(short_help="Analyze genome methylation data.")
@click.option("--meta", is_flag=True, default=False, help="If provided, analyze as metagenomic data; otherwise, analyze as a single genome.")
@click.option("--fna-file", "-f", required=True, type=click.Path(exists=True), help="Path to the .fna file of the genome.")
@click.option("--barcode-map-file", "-b", required=True, type=click.Path(exists=True), help="TSV mapping barcodes to treatments and samples with no header (e.g. 'barcode\ttreatment\tsample').")
@click.option("--methylation-data-dir", "-m", required=True, type=click.Path(exists=True), help="Directory containing .bed files generated by the do_methylate script.")
@click.option("--output-dir", "-o", required=True, type=click.Path(), help="Directory to store the analysis results (tables, plots, processed data, etc.).")
@click.option("--coverage", "-c", default=5, show_default=True, help="Minimum coverage threshold for analysis.")
@click.option("--gene-calls", "-g", default="gene-calls.txt", show_default=True, help="Path to gene call file output by anvi'o.")
@click.option("--function-calls", "-u", default="function-calls.txt", show_default=True, help="Path to function annotations file output by anvi'o.")
@click.option("--treatments", "-t", required=True, multiple=True, help="Treatments to be compared must define at least two (e.g. -t top -t bottom).")
@click.option("--treatment-info", "-i", required=True, type=click.Path(exists=True), help="TSV file containing treatment information WITH HEADER. (e.g. 'treatment\treadable_treatment\tcolor\torder').")
def analyze_genome(
    meta: bool,
    fna_file: str,
    barcode_map_file: str,
    methylation_data_dir: str,
    output_dir: str,
    coverage: int,
    gene_calls: str,
    function_calls: str,
    treatments: list[str],
    treatment_info: str
):
    """
    Analyze methylation data generated by the do_methylate script.

    This command:
      1) Loads the genome (FASTA) and the pre-generated .bed files from do_methylate.
      2) Loads barcode→treatment mappings.
      3) Applies any coverage-based filtering, merges or processes the .bed data as needed.
      4) Optionally identifies motifs or does any domain-specific analysis.
      5) Generates plots or final output files.

    Use --meta to indicate metagenomic data analysis instead of single-genome analysis.
    """

    # Convert click paths to Path objects
    fna_file = Path(fna_file)
    barcode_map_file = Path(barcode_map_file)
    methylation_data_dir = Path(methylation_data_dir)
    output_dir = Path(output_dir)
    gene_calls = Path(gene_calls)
    function_calls = Path(function_calls)
    treatment_info = Path(treatment_info)

    # Ensure output directories exist
    output_dir.mkdir(parents=True, exist_ok=True)

    # Determine analysis mode
    if meta:
        click.echo("Running in metagenomic mode.")
    else:
        click.echo("Running in single-genome mode.")

    # Log input info
    click.echo(f"Genome FASTA: {fna_file}")
    click.echo(f"Barcode→Treatment→Sample TSV: {barcode_map_file}")
    click.echo(f"Loading methylation .bed files from: {methylation_data_dir}")
    click.echo(f"Outputs will be placed in: {output_dir}")
    click.echo(f"Coverage threshold: {coverage}")
    click.echo(f"Gene calls file: {gene_calls}")
    
    genome = Genome(fna_file, methylation_data_dir, gene_calls, function_calls, barcode_map_file, output_dir, treatments, coverage, treatment_info)
    
    # If this genome has Motif objects, proceed:
    motifs = genome.motifs
    if not motifs:
        click.echo("No motifs available to analyze.")
        return

    for motif in motifs:
        click.echo(f"Analyzing motif: {motif.motif} (meth_type={motif.meth_type})")

        # 1) Whole methylome plot for this motif type
        plot_whole_methylome(genome, motif, output_dir)

        # 2) Motif-level methylation across treatments
        plot_motif_methylation_distribution(genome, motif, output_dir)

        # 3) DMR scores heatmap
        plot_dmr_scores_heatmap(genome, motif, output_dir)

        # 4) Parallel categories
        plot_parallel_categories_methylation(genome, motif, output_dir, bins=3)

        # 5) Extract top 10 diff. methylated genes
        extract_diff_methylated_genes(genome, motif, top_n=10)

    click.echo("Analysis complete.")


if __name__ == "__main__":
    cli()