import click
from pathlib import Path
from src.objects.genome import Genome
from src.objects.contig import Contig
from analyze_genome import *
from analyze_contigs import *
from colwellia import *
from mag_eval_plot import *
from src.utilities.utils import parse_treatment_tsv, parse_barcode_tsv
from pelagibacter import *

@click.group(help="A multi-command CLI for methylation analysis.")
@click.pass_context
def cli(ctx):
    """
    The main entry point for our CLI tool.

    Running `python cli.py --help` or `python cli.py -h` will show
    the top-level help, which includes available commands.
    """
    pass


@cli.command(short_help="Analyze genome methylation data.")
@click.option("--fna-file", "-f", required=True, type=click.Path(exists=True), help="Path to the .fna file of the genome.")
@click.option("--barcode-map-file", "-b", required=True, type=click.Path(exists=True), help="TSV mapping barcodes to treatments and samples WITH HEADER (e.g. 'barcode\ttreatment\tsample').")
@click.option("--methylation-data-dir", "-m", required=True, type=click.Path(exists=True), help="Directory containing pileup .bed files for each genome.")
@click.option("--output-dir", "-o", required=True, type=click.Path(), help="Directory to store the analysis results (tables, plots, processed data, etc.).")
@click.option("--coverage", "-c", default=5, show_default=True, help="Minimum coverage threshold for analysis.")
@click.option("--gene-calls", "-g", default="gene-calls.txt", show_default=True, help="Path to gene call file output by anvi'o.")
@click.option("--function-calls", "-u", default="function-calls.txt", show_default=True, help="Path to function annotations file output by anvi'o.")
@click.option("--treatments", "-t", required=True, multiple=True, help="Treatments to be compared must define at least two (e.g. -t top -t bottom).")
@click.option("--treatment-info", "-i", required=True, type=click.Path(exists=True), help="TSV file containing treatment information WITH HEADER. (e.g. 'treatment\treadable_treatment\tcolor\torder').")
def analyze_genome(
    fna_file: str,
    barcode_map_file: str,
    methylation_data_dir: str,
    output_dir: str,
    coverage: int,
    gene_calls: str,
    function_calls: str,
    treatments: list[str],
    treatment_info: str
):
    """
    Analyze methylation data generated by the do_methylate script.

    This command:
      1) Loads the genome (FASTA) and the pre-generated .bed files from do_methylate.
      2) Loads barcode→treatment mappings.
      3) Applies any coverage-based filtering, merges or processes the .bed data as needed.
      4) Optionally identifies motifs or does any domain-specific analysis.
      5) Generates plots or final output files.

    Use --meta to indicate metagenomic data analysis instead of single-genome analysis.
    """

    # Convert click paths to Path objects
    fna_file = Path(fna_file)
    barcode_map_file = Path(barcode_map_file)
    methylation_data_dir = Path(methylation_data_dir)
    output_dir = Path(output_dir)
    gene_calls = Path(gene_calls)
    function_calls = Path(function_calls)
    treatment_info = Path(treatment_info)

    # Ensure output directories exist
    output_dir.mkdir(parents=True, exist_ok=True)
    
    genome = Genome(fna_file, methylation_data_dir, gene_calls, function_calls, barcode_map_file, output_dir, treatments, coverage, treatment_info)
    
    # If this genome has Motif objects, proceed:
    motifs = genome.motifs
    if not motifs:
        click.echo("No motifs available to analyze.")
        return

    for motif in motifs:
        click.echo(f"Analyzing motif: {motif.motif} (meth_type={motif.meth_type})")

        # Whole methylome plot for this motif type
        plot_whole_methylome(genome, motif, output_dir)

        # Motif-level methylation across treatments
        plot_motif_methylation_distribution(genome, motif, output_dir)

        # DMR scores heatmap
        plot_dmr_scores_heatmap(genome, motif, output_dir)

        # Parallel categories
        plot_parallel_categories_methylation(genome, motif, output_dir, bins=3)

        # Extract top diff methylated genes
        trans = extract_motif_data_all_transitions(genome, motif)
        dmrs = extract_diff_methylated_genes(genome, motif, top_n=0)
        if dmrs is not None and trans is not None:
            extract_consensus_genes(genome, trans, dmrs, motif)
        
    # Basic stats file
    write_basic_stats(genome, motifs)

    click.echo("Analysis complete.")


@cli.command(short_help="Analyze metagenome methylation data per contig.")
@click.option("--fna-file", "-f", required=True, type=click.Path(exists=True), help="Path to the .fna file of the metagenome.")
@click.option("--barcode-map-file", "-b", required=True, type=click.Path(exists=True), help="TSV mapping barcodes to treatments and samples WITH HEADER (e.g. 'barcode\ttreatment\tsample').")
@click.option("--methylation-data-dir", "-m", required=True, type=click.Path(exists=True), help="Directory containing pileup .bed files for the metagenome.")
@click.option("--output-dir", "-o", required=True, type=click.Path(), help="Directory to store the analysis results (tables, plots, processed data, etc.).")
@click.option("--coverage", "-c", default=5, show_default=True, help="Minimum coverage threshold for analysis.")
@click.option("--gene-calls", "-g", default="gene-calls.txt", show_default=True, help="Path to gene call file output by anvi'o.")
@click.option("--function-calls", "-u", default="function-calls.txt", show_default=True, help="Path to function annotations file output by anvi'o.")
@click.option("--treatments", "-t", required=True, multiple=True, help="Treatments to be compared must define at least two (e.g. -t top -t bottom).")
@click.option("--treatment-info", "-i", required=True, type=click.Path(exists=True), help="TSV file containing treatment information WITH HEADER. (e.g. 'treatment\treadable_treatment\tcolor\torder').")
@click.option("--contig-taxonomy-tsv", "-x", required=True, type=click.Path(exists=True), help="TSV file mapping contigs to taxonomy.")
@click.option("--taxonomy-generator", "-y", required=True, help="Generator of taxonomy file.")
def analyze_metagenome(
    fna_file: str,
    barcode_map_file: str,
    methylation_data_dir: str,
    output_dir: str,
    coverage: int,
    gene_calls: str,
    function_calls: str,
    treatments: list[str],
    treatment_info: str,
    contig_taxonomy_tsv: str,
    taxonomy_generator: str
):
    # Convert click paths to Path objects
    fna_file = Path(fna_file)
    barcode_map_file = Path(barcode_map_file)
    methylation_data_dir = Path(methylation_data_dir)
    output_dir = Path(output_dir)
    gene_calls = Path(gene_calls)
    function_calls = Path(function_calls)
    treatment_info = Path(treatment_info)
    contig_taxonomy_tsv = Path(contig_taxonomy_tsv)

    # Ensure output directories exist
    output_dir.mkdir(parents=True, exist_ok=True)
    
    genome = Genome(fna_file, methylation_data_dir, gene_calls, function_calls, barcode_map_file, output_dir, treatments, coverage, treatment_info)
    contig_names = genome.sequence.keys()
    contigs = [Contig(genome, contig_name, contig_taxonomy_tsv, taxonomy_generator, is_viral=False) for contig_name in contig_names]

    df = plot_contig_motif_heatmap_stats(contigs)
    extract_diff_methylated_genes_contigs(contigs)
    write_basic_stats_about_contigs(contigs, df)


@cli.command(short_help="Analyze viruses methylation data, assumes one virus per contig.")
@click.option("--fna-file", "-f", required=True, type=click.Path(exists=True), help="Path to the .fna file containing all viruses.")
@click.option("--barcode-map-file", "-b", required=True, type=click.Path(exists=True), help="TSV mapping barcodes to treatments and samples WITH HEADER (e.g. 'barcode\ttreatment\tsample').")
@click.option("--methylation-data-dir", "-m", required=True, type=click.Path(exists=True), help="Directory containing pileup .bed files for the viruses.")
@click.option("--output-dir", "-o", required=True, type=click.Path(), help="Directory to store the analysis results (tables, plots, processed data, etc.).")
@click.option("--coverage", "-c", default=5, show_default=True, help="Minimum coverage threshold for analysis.")
@click.option("--gene-calls", "-g", default="gene-calls.txt", show_default=True, help="Path to gene call file output by anvi'o.")
@click.option("--function-calls", "-u", default="function-calls.txt", show_default=True, help="Path to function annotations file output by anvi'o.")
@click.option("--treatments", "-t", required=True, multiple=True, help="Treatments to be compared must define at least two (e.g. -t top -t bottom).")
@click.option("--treatment-info", "-i", required=True, type=click.Path(exists=True), help="TSV file containing treatment information WITH HEADER. (e.g. 'treatment\treadable_treatment\tcolor\torder').")
@click.option("--genomad-summary-tsv", "-x", required=True, type=click.Path(exists=True), help="virus_summary TSV file output by genomad.")
@click.option("--taxonomy-generator", "-y", required=True, help="Generator of taxonomy file.")
def analyze_viruses(
    fna_file: str,
    barcode_map_file: str,
    methylation_data_dir: str,
    output_dir: str,
    coverage: int,
    gene_calls: str,
    function_calls: str,
    treatments: list[str],
    treatment_info: str,
    genomad_summary_tsv: str,
    taxonomy_generator: str
):
    
    # Convert click paths to Path objects
    fna_file = Path(fna_file)
    barcode_map_file = Path(barcode_map_file)
    methylation_data_dir = Path(methylation_data_dir)
    output_dir = Path(output_dir)
    gene_calls = Path(gene_calls)
    function_calls = Path(function_calls)
    treatment_info = Path(treatment_info)
    genomad_summary_tsv = Path(genomad_summary_tsv)

    # Ensure output directories exist
    output_dir.mkdir(parents=True, exist_ok=True)
    
    genome = Genome(fna_file, methylation_data_dir, gene_calls, function_calls, barcode_map_file, output_dir, treatments, coverage, treatment_info)
    contig_names = genome.sequence.keys()
    contigs = [Contig(genome, contig_name, genomad_summary_tsv, taxonomy_generator, is_viral=True) for contig_name in contig_names]
    
    df = plot_contig_motif_heatmap_stats(contigs)
    extract_diff_methylated_genes_contigs(contigs)
    write_basic_stats_about_contigs(contigs, df)
    
    
@cli.command(short_help="Plot quality and coverage data for MAGs.")
@click.option("--checkm-tsv", "-q", required=True, type=click.Path(exists=True), help="CheckM2 quality_report.tsv file.")
@click.option("--output-dir", "-o", required=True, type=click.Path(), help="Directory to store the analysis results (tables, plots, processed data, etc.).")
@click.option("--coverm-path", "-c", required=True, type=click.Path(exists=True), help="Path to the coverm coverage file.")
@click.option("--treatment-info", "-i", required=True, type=click.Path(exists=True), help="TSV file containing treatment information WITH HEADER. (e.g. 'treatment\treadable_treatment\tcolor\torder').")
@click.option("--barcode-map-file", "-b", required=True, type=click.Path(exists=True), help="TSV mapping barcodes to treatments and samples WITH HEADER (e.g. 'barcode\ttreatment\tsample').")
def quality_coverage(checkm_tsv: str, output_dir: str, coverm_path: int, treatment_info: str, barcode_map_file: str):
    checkm_tsv = Path(checkm_tsv)
    coverm_path = Path(coverm_path)
    output_dir = Path(output_dir)
    
    # Ensure output directories exist
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Parse treatment info the get barcode replicate map
    treatment_name_map, _, treatment_order_map = parse_treatment_tsv(treatment_info)
    barcode_treatment_map, _ = parse_barcode_tsv(barcode_map_file)

    plot_coverage(coverm_path, output_dir, treatment_name_map, barcode_treatment_map, treatment_order_map)
    plot_mag_qual(checkm_tsv, output_dir)


@cli.command(short_help="Plot barplot of microbemod result.")
@click.option("--microbemod-tsv", "-t", required=True, type=click.Path(exists=True), help="MicrobeMod output file.")
@click.option("--output-dir", "-o", required=True, type=click.Path(), help="Directory to store the analysis results (tables, plots, processed data, etc.).")
@click.option("--title-name", "-n", required=True, help="Title name for the plot.")
@click.option("--methylation-data-dir", "-m", required=True, type=click.Path(exists=True), help="Directory containing pileup .bed files for the viruses.")
def microbemod(microbemod_tsv: str, output_dir: str, title_name: str, methylation_data_dir: str):
    microbemod_tsv = Path(microbemod_tsv)
    methylation_data_dir = Path(methylation_data_dir)
    output_dir = Path(output_dir)
    
    # Ensure output directories exist
    output_dir.mkdir(parents=True, exist_ok=True)
    
    plot_microbemod(microbemod_tsv, output_dir, title_name)
    cross_microbemod_identified_motifs(microbemod_tsv, methylation_data_dir, output_dir)


@cli.command(short_help="Analyze colwellia experiment methylation data.")
@click.option("--fna-file", "-f", required=True, type=click.Path(exists=True), help="Path to the .fna file of the genome.")
@click.option("--barcode-map-file", "-b", required=True, type=click.Path(exists=True), help="TSV mapping barcodes to treatments and samples WITH HEADER (e.g. 'barcode\ttreatment\tsample').")
@click.option("--methylation-data-dir", "-m", required=True, type=click.Path(exists=True), help="Directory containing pileup .bed files for each genome.")
@click.option("--output-dir", "-o", required=True, type=click.Path(), help="Directory to store the analysis results (tables, plots, processed data, etc.).")
@click.option("--coverage", "-c", default=30, show_default=True, help="Minimum coverage threshold for analysis.")
@click.option("--gene-calls", "-g", default="gene-calls.txt", show_default=True, help="Path to gene call file output by anvi'o.")
@click.option("--function-calls", "-u", default="function-calls.txt", show_default=True, help="Path to function annotations file output by anvi'o.")
@click.option("--treatments", "-t", required=True, multiple=True, help="Treatments to be compared must define at least two (e.g. -t top -t bottom).")
@click.option("--treatment-info", "-i", required=True, type=click.Path(exists=True), help="TSV file containing treatment information WITH HEADER. (e.g. 'treatment\treadable_treatment\tcolor\torder').")
def analyze_colwellia(
    fna_file: str,
    barcode_map_file: str,
    methylation_data_dir: str,
    output_dir: str,
    coverage: int,
    gene_calls: str,
    function_calls: str,
    treatments: tuple[str],
    treatment_info: str
):
    """
    Analyze methylation data generated by the do_methylate script.

    This command:
      1) Loads the genome (FASTA) and the pre-generated .bed files from do_methylate.
      2) Loads barcode→treatment mappings.
      3) Applies any coverage-based filtering, merges or processes the .bed data as needed.
      4) Optionally identifies motifs or does any domain-specific analysis.
      5) Generates plots or final output files.

    Use --meta to indicate metagenomic data analysis instead of single-genome analysis.
    """

    # Convert click paths to Path objects
    fna_file = Path(fna_file)
    barcode_map_file = Path(barcode_map_file)
    methylation_data_dir = Path(methylation_data_dir)
    output_dir = Path(output_dir)
    gene_calls = Path(gene_calls)
    function_calls = Path(function_calls)
    treatment_info = Path(treatment_info)

    # Ensure output directories exist
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Remove 55S13 from treatments if it exists
    treatments = list(treatments)
    genome = Genome(fna_file, methylation_data_dir, gene_calls, function_calls, barcode_map_file, output_dir, treatments, coverage, treatment_info)
    
    # If this genome has Motif objects, proceed:
    motifs = genome.motifs
    if not motifs:
        click.echo("No motifs available to analyze.")
        return

    for motif in motifs:
        click.echo(f"Analyzing motif: {motif.motif} (meth_type={motif.meth_type})")

        # plot_number_of_positions_by_coverage_colwellia(motif, output_dir)

        # plot_whole_methylome_colwellia(motif, output_dir)
        
        # plot_motif_methylation_distribution_colwellia(motif, output_dir)        

        # plot_dmr_scores_heatmap_colwellia(motif, output_dir)
        
        # write_genbank_features_near_motifs(motif)
        
        # extract_diff_methylated_genes_colwellia(motif)
        
        # motif_distribution(motif)
                
        motif_functional_enrichment(motif)
        
        find_important_features(motif, True)
        find_important_features(motif, False)

        # fraction_investigation(motif)

        # do_stats(motif)
        
        frac_investigation_with_stats(motif)
        
        # write_promoter_functions(motif)
                
    # Basic stats file
    write_basic_stats_colwellia(genome, motifs)

    click.echo("Analysis complete.")


@cli.command(short_help="Analyze colwellia experiment methylation data.")
@click.option("--fna-file", "-f", required=True, type=click.Path(exists=True), help="Path to the .fna file of the genome.")
@click.option("--barcode-map-file", "-b", required=True, type=click.Path(exists=True), help="TSV mapping barcodes to treatments and samples WITH HEADER (e.g. 'barcode\ttreatment\tsample').")
@click.option("--methylation-data-dir", "-m", required=True, type=click.Path(exists=True), help="Directory containing pileup .bed files for each genome.")
@click.option("--output-dir", "-o", required=True, type=click.Path(), help="Directory to store the analysis results (tables, plots, processed data, etc.).")
@click.option("--coverage", "-c", default=30, show_default=True, help="Minimum coverage threshold for analysis.")
@click.option("--gene-calls", "-g", default="gene-calls.txt", show_default=True, help="Path to gene call file output by anvi'o.")
@click.option("--function-calls", "-u", default="function-calls.txt", show_default=True, help="Path to function annotations file output by anvi'o.")
@click.option("--treatments", "-t", required=True, multiple=True, help="Treatments to be compared (e.g. -t top -t bottom).")
@click.option("--treatment-info", "-i", required=True, type=click.Path(exists=True), help="TSV file containing treatment information WITH HEADER. (e.g. 'treatment\treadable_treatment\tcolor\torder').")
def analyze_pelagibacter(
    fna_file: str,
    barcode_map_file: str,
    methylation_data_dir: str,
    output_dir: str,
    coverage: int,
    gene_calls: str,
    function_calls: str,
    treatments: tuple[str],
    treatment_info: str
):
    """
    Analyze methylation data generated by the do_methylate script.

    This command:
      1) Loads the genome (FASTA) and the pre-generated .bed files from do_methylate.
      2) Loads barcode→treatment mappings.
      3) Applies any coverage-based filtering, merges or processes the .bed data as needed.
      4) Optionally identifies motifs or does any domain-specific analysis.
      5) Generates plots or final output files.

    Use --meta to indicate metagenomic data analysis instead of single-genome analysis.
    """

    # Convert click paths to Path objects
    fna_file = Path(fna_file)
    barcode_map_file = Path(barcode_map_file)
    methylation_data_dir = Path(methylation_data_dir)
    output_dir = Path(output_dir)
    gene_calls = Path(gene_calls)
    function_calls = Path(function_calls)
    treatment_info = Path(treatment_info)

    # Ensure output directories exist
    output_dir.mkdir(parents=True, exist_ok=True)
    
    treatments = list(treatments)
    genome = Genome(fna_file, methylation_data_dir, gene_calls, function_calls, barcode_map_file, output_dir, treatments, coverage, treatment_info)
    
    # If this genome has Motif objects, proceed:
    motifs = genome.motifs
    if not motifs:
        click.echo("No motifs available to analyze.")
        return

    for motif in motifs:
        click.echo(f"Analyzing motif: {motif.motif} (meth_type={motif.meth_type})")

        plot_whole_methylome_pelagibacter(motif)
        
        # Print number of sites meeting coverage
        df = motif.data(in_every_treatment=False)
        if df is None:
            return 
        df = df.collect()
        df = df.group_by("treatment").agg(pl.struct(["contig", "strand", "position"]).n_unique().alias("count"))
        print(f"Positions passing: {motif.data().collect().height}")
        print(f"Coverage mean: {motif.data(normalize=False).collect().with_columns((pl.col(motif.meth_type) + pl.col(motif.canonical_base)).alias('coverage')).select(pl.col('coverage').mean()).item()}")
        print(f"Total positions: {motif.positions.collect().height}")


if __name__ == "__main__":
    cli()