import click
from pathlib import Path
from src.objects.genome import Genome
from colwellia import *
from pelagibacter import *

@click.group(help="A multi-command CLI for methylation analysis.")
@click.pass_context
def cli(ctx):
    """
    The main entry point for our CLI tool.

    Running `python cli.py --help` or `python cli.py -h` will show
    the top-level help, which includes available commands.
    """
    pass


@cli.command(short_help="Analyze colwellia experiment methylation data.")
@click.option("--fna-file", "-f", required=True, type=click.Path(exists=True), help="Path to the .fna file of the genome.")
@click.option("--barcode-map-file", "-b", required=True, type=click.Path(exists=True), help="TSV mapping barcodes to treatments and samples WITH HEADER (e.g. 'barcode\ttreatment\tsample').")
@click.option("--methylation-data-dir", "-m", required=True, type=click.Path(exists=True), help="Directory containing pileup .bed files for each genome.")
@click.option("--output-dir", "-o", required=True, type=click.Path(), help="Directory to store the analysis results (tables, plots, processed data, etc.).")
@click.option("--coverage", "-c", default=30, show_default=True, help="Minimum coverage threshold for analysis.")
@click.option("--gene-calls", "-g", default="gene-calls.txt", show_default=True, help="Path to gene call file output by anvi'o.")
@click.option("--function-calls", "-u", default="function-calls.txt", show_default=True, help="Path to function annotations file output by anvi'o.")
@click.option("--treatments", "-t", required=True, multiple=True, help="Treatments to be compared must define at least two (e.g. -t top -t bottom).")
@click.option("--treatment-info", "-i", required=True, type=click.Path(exists=True), help="TSV file containing treatment information WITH HEADER. (e.g. 'treatment\treadable_treatment\tcolor\torder').")
def analyze_colwellia(
    fna_file: str,
    barcode_map_file: str,
    methylation_data_dir: str,
    output_dir: str,
    coverage: int,
    gene_calls: str,
    function_calls: str,
    treatments: tuple[str],
    treatment_info: str
):
    """
    Analyze methylation data generated by the do_methylate script.

    This command:
      1) Loads the genome (FASTA) and the pre-generated .bed files from do_methylate.
      2) Loads barcode→treatment mappings.
      3) Applies any coverage-based filtering, merges or processes the .bed data as needed.
      4) Optionally identifies motifs or does any domain-specific analysis.
      5) Generates plots or final output files.

    Use --meta to indicate metagenomic data analysis instead of single-genome analysis.
    """

    # Convert click paths to Path objects
    fna_file = Path(fna_file)
    barcode_map_file = Path(barcode_map_file)
    methylation_data_dir = Path(methylation_data_dir)
    output_dir = Path(output_dir)
    gene_calls = Path(gene_calls)
    function_calls = Path(function_calls)
    treatment_info = Path(treatment_info)

    # Ensure output directories exist
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Remove 55S13 from treatments if it exists
    treatments = list(treatments)
    genome = Genome(fna_file, methylation_data_dir, gene_calls, function_calls, barcode_map_file, output_dir, treatments, coverage, treatment_info)
    
    # If this genome has Motif objects, proceed:
    motifs = genome.motifs
    if not motifs:
        click.echo("No motifs available to analyze.")
        return

    for motif in motifs:
        click.echo(f"Analyzing motif: {motif.motif} (meth_type={motif.meth_type})")

        # Diagnostic and metadata
        # plot_number_of_positions_by_coverage_colwellia(motif, output_dir)
        # write_genbank_features_near_motifs(motif)
        # plot_motif_methylation_distribution_colwellia(motif, output_dir)        

        # Whole methylome view 
        # plot_whole_methylome_colwellia(motif, output_dir)
        # plot_whole_methylome_colwellia(motif, output_dir, True)                
        
        # Motif distribution                
        # motif_distribution(motif)
        # motif_functional_enrichment(motif)
                                
        # Statistics        
        do_whole_methylome_stats(motif, alpha=0.05)
        # ensemble_df = ensemble_significant_features(motif)
        # frac_groups_df = frac_investigation_with_stats(motif)
        # seq_df = write_frac_sequence_with_stats(motif)
        # synthesis(motif, ensemble_df, frac_groups_df, seq_df)
        # annotated_pca(motif)
        # colinear_features(motif)
        # regulatory_candidates(motif)

        # for pos in [4001064, 5027643, 5367876]:
            # position_stats_plots(motif, pos)
        
        # plot_stat_dists(motif)

    # Basic stats file
    # write_basic_stats_colwellia(genome, motifs)

    click.echo("Analysis complete.")


@cli.command(short_help="Analyze pelagibacter experiment methylation data.")
@click.option("--fna-file", "-f", required=True, type=click.Path(exists=True), help="Path to the .fna file of the genome.")
@click.option("--barcode-map-file", "-b", required=True, type=click.Path(exists=True), help="TSV mapping barcodes to treatments and samples WITH HEADER (e.g. 'barcode\ttreatment\tsample').")
@click.option("--methylation-data-dir", "-m", required=True, type=click.Path(exists=True), help="Directory containing pileup .bed files for each genome.")
@click.option("--output-dir", "-o", required=True, type=click.Path(), help="Directory to store the analysis results (tables, plots, processed data, etc.).")
@click.option("--coverage", "-c", default=30, show_default=True, help="Minimum coverage threshold for analysis.")
@click.option("--gene-calls", "-g", default="gene-calls.txt", show_default=True, help="Path to gene call file output by anvi'o.")
@click.option("--function-calls", "-u", default="function-calls.txt", show_default=True, help="Path to function annotations file output by anvi'o.")
@click.option("--treatments", "-t", required=True, multiple=True, help="Treatments to be compared (e.g. -t top -t bottom).")
@click.option("--treatment-info", "-i", required=True, type=click.Path(exists=True), help="TSV file containing treatment information WITH HEADER. (e.g. 'treatment\treadable_treatment\tcolor\torder').")
def analyze_pelagibacter(
    fna_file: str,
    barcode_map_file: str,
    methylation_data_dir: str,
    output_dir: str,
    coverage: int,
    gene_calls: str,
    function_calls: str,
    treatments: tuple[str],
    treatment_info: str
):
    """
    Analyze methylation data generated by the do_methylate script.

    This command:
      1) Loads the genome (FASTA) and the pre-generated .bed files from do_methylate.
      2) Loads barcode→treatment mappings.
      3) Applies any coverage-based filtering, merges or processes the .bed data as needed.
      4) Optionally identifies motifs or does any domain-specific analysis.
      5) Generates plots or final output files.

    Use --meta to indicate metagenomic data analysis instead of single-genome analysis.
    """

    # Convert click paths to Path objects
    fna_file = Path(fna_file)
    barcode_map_file = Path(barcode_map_file)
    methylation_data_dir = Path(methylation_data_dir)
    output_dir = Path(output_dir)
    gene_calls = Path(gene_calls)
    function_calls = Path(function_calls)
    treatment_info = Path(treatment_info)

    # Ensure output directories exist
    output_dir.mkdir(parents=True, exist_ok=True)
    
    treatments = list(treatments)
    genome = Genome(fna_file, methylation_data_dir, gene_calls, function_calls, barcode_map_file, output_dir, treatments, coverage, treatment_info)
    
    # If this genome has Motif objects, proceed:
    motifs = genome.motifs
    if not motifs:
        click.echo("No motifs available to analyze.")
        return

    for motif in motifs:
        click.echo(f"Analyzing motif: {motif.motif} (meth_type={motif.meth_type})")

        plot_whole_methylome_pelagibacter(motif)
        
        # Print number of sites meeting coverage
        df = motif.data(in_every_treatment=False)
        if df is None:
            return 
        df = df.collect()
        df = df.group_by("treatment").agg(pl.struct(["contig", "strand", "position"]).n_unique().alias("count"))
        print(f"Positions passing: {motif.data().collect().height}")
        print(f"Coverage mean: {motif.data(normalize=False).collect().with_columns((pl.col(motif.meth_type) + pl.col(motif.canonical_base)).alias('coverage')).select(pl.col('coverage').mean()).item()}")
        print(f"Total positions: {motif.positions.collect().height}")


if __name__ == "__main__":
    cli()